const EQUIPOS = [
  'Albania',
  'Andorra',
  'Armenia',
  'Austria',
  'Azerbaijan',
  'Bielorusia',
  'Belgica',
  'Bosnia & Herzegovina',
  'Bulgaria',
  'Croacia',
  'Chipre',
  'Republica Checa',
  'Dinamarca',
  'Inglaterra',
  'Estonia',
  'Islas Feroe',
  'Finlandia',
  'Francia',
  'Georgia',
  'Alemania',
  'Gibraltar',
  'Grecia',
  'Hungria',
  'Islandia',
  'Irlanda',
  'Israel',
  'Italia',
  'Kazakhstan',
  'Kosovo',
  'Letonia',
  'Liechenstein',
  'Lituania',
  'Luxemburgo',
  'Malta',
  'Moldavia',
  'Montenegro',
  'Holanda',
  'Macedonia Norte',
  'Irlanda Norte',
  'Noruega',
  'Polonia',
  'Portugal',
  'Rumania',
  'Rusia',
  'San Marino',
  'Escocia',
  'Serbia',
  'Eslovaquia',
  'Eslovenia',
  'España',
  'Suecia',
  'Suiza',
  'Turquia',
  'Ukrania',
  'Gales',
];

const LETRAS_GRUPOS = ['A', 'B', 'C', 'D', 'E', 'F'];

export { EQUIPOS, LETRAS_GRUPOS };
