const EQUIPOS = [
  'Albania',
  'Alemania',
  'Andorra',
  'Armenia',
  'Austria',
  'Azerbaijan',
  'Belgica',
  'Bielorusia',
  'Bosnia',
  'Bulgaria',
  'Chipre',
  'Croacia',
  'Dinamarca',
  'Escocia',
  'Eslovaquia',
  'Eslovenia',
  'España',
  'Estonia',
  'Finlandia',
  'Francia',
  'Gales',
  'Georgia',
  'Gibraltar',
  'Grecia',
  'Holanda',
  'Hungria',
  'Inglaterra',
  'Irlanda',
  'Irlanda Norte',
  'Islandia',
  'Islas Feroe',
  'Israel',
  'Italia',
  'Kazakhstan',
  'Kosovo',
  'Letonia',
  'Liechtenstein',
  'Lituania',
  'Luxemburgo',
  'Macedonia Norte',
  'Malta',
  'Moldavia',
  'Montenegro',
  'Noruega',
  'Polonia',
  'Portugal',
  'Republica Checa',
  'Rumania',
  'Rusia',
  'San Marino',
  'Serbia',
  'Suecia',
  'Suiza',
  'Turquia',
  'Ucrania',
];

const LETRAS_GRUPOS = ['A', 'B', 'C', 'D', 'E', 'F'];

export { EQUIPOS, LETRAS_GRUPOS };
